### ISSUE TITLE
Conflict with main class

### ISSUE THREAD

**Issue by pedrro** [googleapis/java-language#267]
#### Environment details 

1. Specify the API at the beginning of the title. For example, "BigQuery: ..."): Google Natural Language - java
2. OS type and version: Ubuntu 18.04
3. Java version: java 8
4. language version(s): 1.101.3

#### Steps to reproduce

  1. Create a project
  2. Add GNL dependency
  3. Create a class with main method
  4. Generate a jar
  5. Run the jar with command `java -jar yourJar.jar`

An error will be reproduced:
Error: Could not find or load main class Application

#### Code example

```java
public class Application {
    
    public static void main(String[] args) {
        System.out.println("hello world");
    }
}

```

#### Stack trace
```
Error: Could not find or load main class Application
```

#### Any additional information below
Hi all, I started to use the library this weekend, It runs well on the IDE(IntelliJ Idea) but when I'm generating the jar the main class is not found.
But the strange is that it's able to find when I comment the GNL dependency on build.gradle

Following these steps guarantees the quickest resolution possible.

Thanks!

**Comment by athakor** [comment]
@pedrro The `-jar` option only works if the JAR file is an `executable `JAR file, which means it must have a manifest file with a `Main-Class` attribute in it. See [Packaging Programs in JAR Files](https://docs.oracle.com/javase/tutorial/deployment/jar/index.html) to learn how to create an executable JAR.

To run the above example you need to create the executable JAR. So for that you need to add the following configuration in your `build.gradle` file.

```javascript
jar {
    manifest {
        attributes(
                'Main-Class': 'Application'
        )
    }
}
```

Then run `java -jar yourJar.jar`

**Output:**
![Output](https://user-images.githubusercontent.com/49403056/96832129-e3b80700-145b-11eb-8d3a-bda8a773e1ed.PNG)

**Comment by pedrro** [comment]
hi @athakor thanks to answer me.
I did exactly as you mentioned, and got the same error.

To make more clear about how i'm reproducing it, I created a repo with all the steps on readme
https://github.com/pedrro/gnl-example

please take a look

**Comment by b-loved-dreamer** [comment]
Hi @pedrro, I tried your steps and was able to repro the stated error. I will escalate this issue to appropriate team and come back to you once I hear from them. Thank you for providing clear steps to repro this issue.

**Comment by athakor** [comment]
Hi @pedrro, I cloned your repo and performed the steps which you had mention in **README.md** and was able to reproduced the issue. To resolve these issue or to make it runnable you need to perform the following steps :

**Step-1 :** Please replace your `build.gradle` file with the following entries and please make sure your` build.gradle` file exactly the same which i had suggested.

**build.gradle**
```
plugins {
    id 'java'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    compile group: 'net.sourceforge.htmlunit', name: 'htmlunit', version: '2.4'
    compile group: 'com.google.cloud', name: 'google-cloud-language', version: '1.101.3'

    testCompile group: 'junit', name: 'junit', version: '4.12'
    testCompile group: 'org.mockito', name: 'mockito-core', version: '3.4.6'
}

jar {
    manifest {
        attributes(
                'Main-Class': 'Application'
        )
    }
}
```

**Step-2 :**` ./gradlew clean build`

**Step-3 :**` java -jar build/libs/gnl-example-1.0-SNAPSHOT.jar`

You can see the steps in snapshot which i had performed to run your code successfully.

![Output](https://user-images.githubusercontent.com/49403056/96986842-d4aa8500-153f-11eb-8dca-3c75f38621e2.PNG)

**Comment by b-loved-dreamer** [comment]
I tested @athakor's solution and it works on my end. Just remove the ```    from {
        configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }}``` from the ```jar```, rebuild and it will work.

**Comment by pedrro** [comment]
Hi all, thanks for the feedback, it works for me too, I just can't figure out why this line that was removed causes the problem.
But thanks for all the support, this issue can be closed.
